[project]
name = "fuelhook"
version = "3.0"
description = "A 7-Elevel fuel price alert script"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "apprise==1.9.7",
]

[dependency-groups]
dev = [
    "pytest==9.0.2",
]
